import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static Map<String, Map<String, String>> _localizedStrings = {
    'ru': {
      'letsgetstarted': "Давайте начнем",
      'descriptiononDevine':
          "Lorem Ipsum - это просто фиктивный текст для полиграфической промышленности.",
      'createaccount': "Cоздать аккаунт",
      'login': "Авторизоваться",
      'registration': "Регистрация",
      'descriptionOnRegistration':
          "Lorem Ipsum - это просто фиктивный текст для полиграфической промышленности.",
      'ContinueOnRegistration': "Продолжить",
      'LoginOnLogin': "Авторизоваться",
      'DescriptionOnLogin':
          "Lorem Ipsum - это просто фиктивный текст для полиграфической промышленности.",
      'ContinueOnLogin': "Продолжить",
      'MenuItemsOneOnHome': "Полка",
      'MenuItemsTwoOnHome': "Магазин",
      'MenuItemsThreeOnHome': "Портфель",
      'MenuItemsFourOnHome': "Общение",
      'MyBookBookshelf': "Мои книги",
      'WishlistedBooksBookshelf': "Список желаний",
      'BookShareGenreList1': "Научная фантастика",
      'BookShareGenreList2': "Фэнтези",
      'BookShareGenreList3': "Детектив",
      'BookShareGenreList4': "Романтика",
      'BookShareGenreList5': "Триллер",
      'BookShareGenreList6': "Ужасы",
      'BookShareGenreList7': "Приключения",
      'BookShareGenreList8': "Научно-популярная литература",
      'BookShareGenreList9': "Биография",
      'BookShareGenreList10': "Историческая проза",
      'BookShareGenreList11': "Дистопия",
      'BookShareGenreList12': "Поэзия",
      'BookShareGenreList13': "Саморазвитие",
      'BookShareGenreList14': "Кулинарная книга",
      'BookShareGenreList15': "Графическая новелла",
      'BookShareGenreList16': "Молодежная литература",
      'BookShareGenreList17': "Детская литература",
      'MyBagOnBag': "Мой портфель",
      'DrawerOnHomeToHomeScreens': "Домашняя страница",
      'DrawerOnNewCollectionsToHomeScreens': "Новые коллекции",
      'DrawerOnEditorsToHomeScreens': "Рекомендации редактора",
      'DrawerOnTopDealseToHomeScreens': "Лучшие предложения",
      'DrawerOnNotificationsToHomeScreens': "Уведомления",
      'DrawerOnSettingToHomeScreens': "Настройки",
      'TitleOnNotificationsTonotification': "Уведомления",
      'TitleOnScanntoScannerQr': "Сканировать QR-код",
      'ShowOnScanntoScannerQr': "Показать",
      'ScanOnScanntoScannerQr': "Сканировать",
      'SettingsTitleToSettings': "Настройки",
      'AccountToSettings': "Аккаунт",
      'SettingsLabelToSettings': "Настройки",
      'LanguageLabelToSettings': "Язык",
      'NotificationsLabelToSettings': "Уведомления",
      'DarkModeLabelToSettings': "Темный режим",
      'HelpLabelToSettings': "Помощь",
    },
    'uk': {
      "letsgetstarted": "Давайте начнем",
      "descriptiononDevine":
          "Lorem Ipsum - это просто фиктивный текст для полиграфической промышленности.",
      "createaccount": "Cоздать аккаунт",
      "login": "Авторизоваться",
      "registration": "Регистрация",
      "descriptionOnRegistration":
          "Lorem Ipsum - это просто фиктивный текст для полиграфической промышленности.",
      "ContinueOnRegistration": "Продолжить",
      "LoginOnLogin": "Авторизоваться",
      "DescriptionOnLogin":
          "Lorem Ipsum - это просто фиктивный текст для полиграфической промышленности.",
      "ContinueOnLogin": "Продолжить",
      "MenuItemsOneOnHome": "Полка",
      "MenuItemsTwoOnHome": "Магазин",
      "MenuItemsThreeOnHome": "Портфель",
      "MenuItemsFourOnHome": "Общение",
      "MyBookBookshelf": "Мої книги",
      "WishlistedBooksBookshelf": "Список желань",
      "BookShareGenreList1": "Наукова фантастика",
      "BookShareGenreList2": "Фентезі",
      "BookShareGenreList3": "Детектив",
      "BookShareGenreList4": "Романтика",
      "BookShareGenreList5": "Трилер",
      "BookShareGenreList6": "Жахи",
      "BookShareGenreList7": "Пригоди",
      "BookShareGenreList8": "Науково-популярна література",
      "BookShareGenreList9": "Біографія",
      "BookShareGenreList10": "Історична проза",
      "BookShareGenreList11": "Дистопія",
      "BookShareGenreList12": "Поезія",
      "BookShareGenreList13": "Саморозвиток",
      "BookShareGenreList14": "Кулінарна книга",
      "BookShareGenreList15": "Графічна новела",
      "BookShareGenreList16": "Молодіжна література",
      "BookShareGenreList17": "Дитяча література",
      "MyBagOnBag": "Мій портфель",
      "DrawerOnHomeToHomeScreens": "Домашня сторінка",
      "DrawerOnNewCollectionsToHomeScreens": "Нові колекції",
      "DrawerOnEditorsToHomeScreens": "Рекомендації редактора",
      "DrawerOnTopDealseToHomeScreens": "Лучшие пропозиції",
      "DrawerOnNotificationsToHomeScreens": "Сповіщення",
      "DrawerOnSettingToHomeScreens": "Налаштування",
      "TitleOnNotificationsTonotification": "Сповіщення",
      "TitleOnScanntoScannerQr": "Сканувати QR-код",
      "ShowOnScanntoScannerQr": "Показати",
      "ScanOnScanntoScannerQr": "Сканувати",
      "SettingsTitleToSettings": "Налаштування",
      "AccountToSettings": "Обліковий запис",
      "SettingsLabelToSettings": "Налаштування",
      "LanguageLabelToSettings": "Мова",
      "NotificationsLabelToSettings": "Сповіщення",
      "DarkModeLabelToSettings": "Темний режим",
      "HelpLabelToSettings": "Допомога"
    },
    'en': {
      "letsgetstarted": "Let's get started",
      "descriptiononDevine":
          "Lorem Ipsum is simply dummy text used in the printing and typesetting industry.",
      "createaccount": "Create account",
      "login": "Log in",
      "registration": "Registration",
      "descriptionOnRegistration":
          "Lorem Ipsum is simply dummy text used in the printing and typesetting industry.",
      "ContinueOnRegistration": "Continue",
      "LoginOnLogin": "Log in",
      "DescriptionOnLogin":
          "Lorem Ipsum is simply dummy text used in the printing and typesetting industry.",
      "ContinueOnLogin": "Continue",
      "MenuItemsOneOnHome": "Shelf",
      "MenuItemsTwoOnHome": "Store",
      "MenuItemsThreeOnHome": "Portfolio",
      "MenuItemsFourOnHome": "Communication",
      "MyBookBookshelf": "My books",
      "WishlistedBooksBookshelf": "Wishlist",
      "BookShareGenreList1": "Science Fiction",
      "BookShareGenreList2": "Fantasy",
      "BookShareGenreList3": "Detective",
      "BookShareGenreList4": "Romance",
      "BookShareGenreList5": "Thriller",
      "BookShareGenreList6": "Horror",
      "BookShareGenreList7": "Adventure",
      "BookShareGenreList8": "Popular Science",
      "BookShareGenreList9": "Biography",
      "BookShareGenreList10": "Historical Fiction",
      "BookShareGenreList11": "Dystopia",
      "BookShareGenreList12": "Poetry",
      "BookShareGenreList13": "Self-Development",
      "BookShareGenreList14": "Cookbook",
      "BookShareGenreList15": "Graphic Novel",
      "BookShareGenreList16": "Young Adult",
      "BookShareGenreList17": "Children's Literature",
      "MyBagOnBag": "My portfolio",
      "DrawerOnHomeToHomeScreens": "Home page",
      "DrawerOnNewCollectionsToHomeScreens": "New collections",
      "DrawerOnEditorsToHomeScreens": "Editor's recommendations",
      "DrawerOnTopDealseToHomeScreens": "Best deals",
      "DrawerOnNotificationsToHomeScreens": "Notifications",
      "DrawerOnSettingToHomeScreens": "Settings",
      "TitleOnNotificationsTonotification": "Notifications",
      "TitleOnScanntoScannerQr": "Scan QR Code",
      "ShowOnScanntoScannerQr": "Show",
      "ScanOnScanntoScannerQr": "Scan",
      "SettingsTitleToSettings": "Settings",
      "AccountToSettings": "Account",
      "SettingsLabelToSettings": "Settings",
      "LanguageLabelToSettings": "Language",
      "NotificationsLabelToSettings": "Notifications",
      "DarkModeLabelToSettings": "Dark Mode",
      "HelpLabelToSettings": "Help"
    },
    'be': {
      "letsgetstarted": "Пачнем",
      "descriptiononDevine":
          "Lorem Ipsum - гэта проста фікцыйны тэкст для друкарскай прамысловасці.",
      "createaccount": "Стварыць уліковы запіс",
      "login": "Увайсці",
      "registration": "Рэгістрацыя",
      "descriptionOnRegistration":
          "Lorem Ipsum - гэта проста фікцыйны тэкст для друкарскай прамысловасці.",
      "ContinueOnRegistration": "Працягнуць",
      "LoginOnLogin": "Увайсці",
      "DescriptionOnLogin":
          "Lorem Ipsum - гэта проста фікцыйны тэкст для друкарскай прамысловасці.",
      "ContinueOnLogin": "Працягнуць",
      "MenuItemsOneOnHome": "Полка",
      "MenuItemsTwoOnHome": "Магазін",
      "MenuItemsThreeOnHome": "Партфель",
      "MenuItemsFourOnHome": "Сувязь",
      "MyBookBookshelf": "Мае кнігі",
      "WishlistedBooksBookshelf": "Спіс жаданняў",
      "BookShareGenreList1": "Навуковая фантастыка",
      "BookShareGenreList2": "Фентезі",
      "BookShareGenreList3": "Дэтэктыў",
      "BookShareGenreList4": "Рамантика",
      "BookShareGenreList5": "Трылер",
      "BookShareGenreList6": "Жахі",
      "BookShareGenreList7": "Прыгоды",
      "BookShareGenreList8": "Папулярная навука",
      "BookShareGenreList9": "Біяграфія",
      "BookShareGenreList10": "Гісторычная проза",
      "BookShareGenreList11": "Дыстопія",
      "BookShareGenreList12": "Паэзія",
      "BookShareGenreList13": "Самарасьвіцце",
      "BookShareGenreList14": "Кулінарная кніга",
      "BookShareGenreList15": "Графічная вучобніца",
      "BookShareGenreList16": "Маладзёжная літаратура",
      "BookShareGenreList17": "Дзіцячая літаратура",
      "MyBagOnBag": "Мой партфель",
      "DrawerOnHomeToHomeScreens": "Галоўная старонка",
      "DrawerOnNewCollectionsToHomeScreens": "Новыя калекцыі",
      "DrawerOnEditorsToHomeScreens": "Рэкамендацыі рэдактара",
      "DrawerOnTopDealseToHomeScreens": "Лепшыя прапазіцыі",
      "DrawerOnNotificationsToHomeScreens": "Спаведзванні",
      "DrawerOnSettingToHomeScreens": "Налады",
      "TitleOnNotificationsTonotification": "Спаведзванні",
      "TitleOnScanntoScannerQr": "Сканаваць QR-код",
      "ShowOnScanntoScannerQr": "Паказаць",
      "ScanOnScanntoScannerQr": "Сканаваць",
      "SettingsTitleToSettings": "Налады",
      "AccountToSettings": "Уліковы запіс",
      "SettingsLabelToSettings": "Налады",
      "LanguageLabelToSettings": "Мова",
      "NotificationsLabelToSettings": "Спаведзванні",
      "DarkModeLabelToSettings": "Цёмны рэжым",
      "HelpLabelToSettings": "Дапамога"
    },
    'kk': {
      "letsgetstarted": "Бастау",
      "descriptiononDevine":
          "Lorem Ipsum - бұл басқа тілдегі пайдаланушылардың жасау және баспа сауда саласындағы қайраткердің қарынды қалдырылған мәтіні.",
      "createaccount": "Тіркелу",
      "login": "Кіру",
      "registration": "Тіркеу",
      "descriptionOnRegistration":
          "Lorem Ipsum - бұл басқа тілдегі пайдаланушылардың жасау және баспа сауда саласындағы қайраткердің қарынды қалдырылған мәтіні.",
      "ContinueOnRegistration": "Жалғастыру",
      "LoginOnLogin": "Кіру",
      "DescriptionOnLogin":
          "Lorem Ipsum - бұл басқа тілдегі пайдаланушылардың жасау және баспа сауда саласындағы қайраткердің қарынды қалдырылған мәтіні.",
      "ContinueOnLogin": "Жалғастыру",
      "MenuItemsOneOnHome": "Раф",
      "MenuItemsTwoOnHome": "Дүкен",
      "MenuItemsThreeOnHome": "Портфель",
      "MenuItemsFourOnHome": "Жылдамдау",
      "MyBookBookshelf": "Менің кітаптарым",
      "WishlistedBooksBookshelf": "Қалауындаған кітаптар",
      "BookShareGenreList1": "Ғылымиялық фантастика",
      "BookShareGenreList2": "Фэнтези",
      "BookShareGenreList3": "Детектив",
      "BookShareGenreList4": "Романтика",
      "BookShareGenreList5": "Триллер",
      "BookShareGenreList6": "Кечеуі",
      "BookShareGenreList7": "Мақсаттар",
      "BookShareGenreList8": "Ғылымнамалы мәтін",
      "BookShareGenreList9": "Биография",
      "BookShareGenreList10": "Тарихи проза",
      "BookShareGenreList11": "Дистопия",
      "BookShareGenreList12": "Поэзия",
      "BookShareGenreList13": "Өзін-өзі жетілдіру",
      "BookShareGenreList14": "Тамақ кітабы",
      "BookShareGenreList15": "Графикалық роман",
      "BookShareGenreList16": "Жасыл жастардың әдебиеті",
      "BookShareGenreList17": "Балалар кітаптары",
      "MyBagOnBag": "Менің портфелім",
      "DrawerOnHomeToHomeScreens": "Басты бет",
      "DrawerOnNewCollectionsToHomeScreens": "Жаңа жинақтар",
      "DrawerOnEditorsToHomeScreens": "Редактордың ұсынымдары",
      "DrawerOnTopDealseToHomeScreens": "Ең жақсы дайындар",
      "DrawerOnNotificationsToHomeScreens": "Хабарландырулар",
      "DrawerOnSettingToHomeScreens": "Параметрлер",
      "TitleOnNotificationsTonotification": "Хабарландырулар",
      "TitleOnScanntoScannerQr": "QR-кодты скандау",
      "ShowOnScanntoScannerQr": "Көрсету",
      "ScanOnScanntoScannerQr": "Скандау",
      "SettingsTitleToSettings": "Параметрлер",
      "AccountToSettings": "Тіркелгі",
      "SettingsLabelToSettings": "Параметрлер",
      "LanguageLabelToSettings": "Тіл",
      "NotificationsLabelToSettings": "Хабарландырулар",
      "DarkModeLabelToSettings": "Қара күй режимі",
      "HelpLabelToSettings": "Көмек"
    },
    'hy': {
      "letsgetstarted": "Սկսենք",
      "descriptiononDevine":
          "Lorem Ipsum - դա պարզապես ռեալաներների տպարանական արդյունքների համար համարվող դումպար տեքստ է:",
      "createaccount": "Գրանցվել",
      "login": "Մուտք",
      "registration": "Գրանցում",
      "descriptionOnRegistration":
          "Lorem Ipsum - դա պարզապես ռեալաներների տպարանական արդյունքների համար համարվող դումպար տեքստ է:",
      "ContinueOnRegistration": "Շարունակել",
      "LoginOnLogin": "Մուտք",
      "DescriptionOnLogin":
          "Lorem Ipsum - դա պարզապես ռեալաներների տպարանական արդյունքների համար համարվող դումպար տեքստ է:",
      "ContinueOnLogin": "Շարունակել",
      "MenuItemsOneOnHome": "Գրաղեցկություն",
      "MenuItemsTwoOnHome": "Խանութ",
      "MenuItemsThreeOnHome": "Պորտֆոլիո",
      "MenuItemsFourOnHome": "Կապ",
      "MyBookBookshelf": "Իմ գրքերը",
      "WishlistedBooksBookshelf": "Ձայնագրված գրքեր",
      "BookShareGenreList1": "Գիտական ֆանտաստիկա",
      "BookShareGenreList2": "Ֆենտեզի",
      "BookShareGenreList3": "Դետեկտիվ",
      "BookShareGenreList4": "Ռոմանտիկա",
      "BookShareGenreList5": "Թրիլեր",
      "BookShareGenreList6": "Էջրանություն",
      "BookShareGenreList7": "Արվեստ",
      "BookShareGenreList8": "Գիտական-հանդիպում",
      "BookShareGenreList9": "Բիոգրաֆիա",
      "BookShareGenreList10": "Պատմական պրոզա",
      "BookShareGenreList11": "Դիստոպիա",
      "BookShareGenreList12": "Պոեզիա",
      "BookShareGenreList13": "Ինքնազրկգայինարարում",
      "BookShareGenreList14": "Խումբարի գիրք",
      "BookShareGenreList15": "Գրաֆիկ վերնագիր",
      "BookShareGenreList16": "Երիտասարդական աշխատանք",
      "BookShareGenreList17": "Երեխայի գրքեր",
      "MyBagOnBag": "Իմ պորտֆել",
      "DrawerOnHomeToHomeScreens": "Գլխավոր էջ",
      "DrawerOnNewCollectionsToHomeScreens": "Նոր հավաստագրություններ",
      "DrawerOnEditorsToHomeScreens": "Խմբագրորդի առաքումներ",
      "DrawerOnTopDealseToHomeScreens": "Լավագույն առաքումներ",
      "DrawerOnNotificationsToHomeScreens": "Ծանուցումներ",
      "DrawerOnSettingToHomeScreens": "Կարգավորումներ",
      "TitleOnNotificationsTonotification": "Ծանուցումներ",
      "TitleOnScanntoScannerQr": "QR-կոդը սկանավորել",
      "ShowOnScanntoScannerQr": "Ցուցադրել",
      "ScanOnScanntoScannerQr": "Սկանավորել",
      "SettingsTitleToSettings": "Կարգավորումներ",
      "AccountToSettings": "Հաշիվ",
      "SettingsLabelToSettings": "Կարգավորումներ",
      "LanguageLabelToSettings": "Լեզվաբառ",
      "NotificationsLabelToSettings": "Ծանուցումներ",
      "DarkModeLabelToSettings": "Մութ ռեժիմ",
      "HelpLabelToSettings": "Օգնություն"
    },
    'ka': {
      "letsgetstarted": "დავიწყოთ",
      "descriptiononDevine":
          "Lorem Ipsum - ეს სამუშაო და დაფეხულებითი პოლგრაფიული პრომო-ინდუსტრიის სამუშაო ტექსტი არის.",
      "createaccount": "რეგისტრაცია",
      "login": "შესვლა",
      "registration": "რეგისტრაცია",
      "descriptionOnRegistration":
          "Lorem Ipsum - ეს სამუშაო და დაფეხულებითი პოლგრაფიული პრომო-ინდუსტრიის სამუშაო ტექსტი არის.",
      "ContinueOnRegistration": "გაგრძელება",
      "LoginOnLogin": "შესვლა",
      "DescriptionOnLogin":
          "Lorem Ipsum - ეს სამუშაო და დაფეხულებითი პოლგრაფიული პრომო-ინდუსტრიის სამუშაო ტექსტი არის.",
      "ContinueOnLogin": "გაგრძელება",
      "MenuItemsOneOnHome": "რაფი",
      "MenuItemsTwoOnHome": "მაღაზია",
      "MenuItemsThreeOnHome": "პორტფელი",
      "MenuItemsFourOnHome": "კომუნიკაცია",
      "MyBookBookshelf": "ჩემი წიგნები",
      "WishlistedBooksBookshelf": "სისხლისადამი წიგნები",
      "BookShareGenreList1": "სამეცნიერო ფანტასტიკა",
      "BookShareGenreList2": "ფენტეზი",
      "BookShareGenreList3": "დეტექტივი",
      "BookShareGenreList4": "რომანტიკა",
      "BookShareGenreList5": "თრილერი",
      "BookShareGenreList6": "საშინელო",
      "BookShareGenreList7": "თავდასხმება",
      "BookShareGenreList8": "პოპულარული სამეცნიერო ლიტერატურა",
      "BookShareGenreList9": "ბიოგრაფია",
      "BookShareGenreList10": "ისტორიული პროზა",
      "BookShareGenreList11": "დისტოპია",
      "BookShareGenreList12": "პოეზია",
      "BookShareGenreList13": "თვალყურება თვალყურება",
      "BookShareGenreList14": "კულინარული წიგნი",
      "BookShareGenreList15": "გრაფიკური წიგნები",
      "BookShareGenreList16": "ახალგაზრდა ლიტერატურა",
      "BookShareGenreList17": "ბავშვთა ლიტერატურა",
      "MyBagOnBag": "ჩემი ჩანთა",
      "DrawerOnHomeToHomeScreens": "სახლი",
      "DrawerOnNewCollectionsToHomeScreens": "ახალი კოლექციები",
      "DrawerOnEditorsToHomeScreens": "რედაქტორის რჩევები",
      "DrawerOnTopDealseToHomeScreens": "საუკეთესო შეთავაზებები",
      "DrawerOnNotificationsToHomeScreens": "შეტყობინებები",
      "DrawerOnSettingToHomeScreens": "პარამეტრები",
      "TitleOnNotificationsTonotification": "შეტყობინებები",
      "TitleOnScanntoScannerQr": "QR კოდის სკანირება",
      "ShowOnScanntoScannerQr": "ჩვენება",
      "ScanOnScanntoScannerQr": "სკანირება",
      "SettingsTitleToSettings": "პარამეტრები",
      "AccountToSettings": "ანგარიში",
      "SettingsLabelToSettings": "პარამეტრები",
      "LanguageLabelToSettings": "ენა",
      "NotificationsLabelToSettings": "შეტყობინებები",
      "DarkModeLabelToSettings": "ბურთული რეჟიმი",
      "HelpLabelToSettings": "დახმარება"
    },
    'az': {
      "letsgetstarted": "Başlayaq",
      "descriptiononDevine":
          "Lorem Ipsum - bu poliqrafiya sənayesi üçün müxtəlif mətnlər üçün istifadə olunan sazlamlı mətnlərdən biridir.",
      "createaccount": "Hesab yarat",
      "login": "Daxil olun",
      "registration": "Qeydiyyat",
      "descriptionOnRegistration":
          "Lorem Ipsum - bu poliqrafiya sənayesi üçün müxtəlif mətnlər üçün istifadə olunan sazlamlı mətnlərdən biridir.",
      "ContinueOnRegistration": "Davam et",
      "LoginOnLogin": "Daxil olun",
      "DescriptionOnLogin":
          "Lorem Ipsum - bu poliqrafiya sənayesi üçün müxtəlif mətnlər üçün istifadə olunan sazlamlı mətnlərdən biridir.",
      "ContinueOnLogin": "Davam et",
      "MenuItemsOneOnHome": "Rəflər",
      "MenuItemsTwoOnHome": "Mağaza",
      "MenuItemsThreeOnHome": "Portfel",
      "MenuItemsFourOnHome": "Əlaqə",
      "MyBookBookshelf": "Mənim kitablarım",
      "WishlistedBooksBookshelf": "İstək siyahısı kitabları",
      "BookShareGenreList1": "Elmi fantastika",
      "BookShareGenreList2": "Fantaziya",
      "BookShareGenreList3": "Detektiv",
      "BookShareGenreList4": "Romantika",
      "BookShareGenreList5": "Triller",
      "BookShareGenreList6": "Ürək sızlatan",
      "BookShareGenreList7": "Macəra",
      "BookShareGenreList8": "Elmi-populyar ədəbiyyat",
      "BookShareGenreList9": "Biografiya",
      "BookShareGenreList10": "Tarixi prosa",
      "BookShareGenreList11": "Düşüncə ədəbiyyatı",
      "BookShareGenreList12": "Şeirlər",
      "BookShareGenreList13": "Özünü inkişaf etdir",
      "BookShareGenreList14": "Mətbəx kitabı",
      "BookShareGenreList15": "Qrafik novella",
      "BookShareGenreList16": "Gənclik ədəbiyyatı",
      "BookShareGenreList17": "Uşaq ədəbiyyatı",
      "MyBagOnBag": "Mənim portfelim",
      "DrawerOnHomeToHomeScreens": "Əsas səhifə",
      "DrawerOnNewCollectionsToHomeScreens": "Yeni kolleksiyalar",
      "DrawerOnEditorsToHomeScreens": "Redaktor tövsiyələri",
      "DrawerOnTopDealseToHomeScreens": "Ən yaxşı təkliflər",
      "DrawerOnNotificationsToHomeScreens": "Bildirişlər",
      "DrawerOnSettingToHomeScreens": "Ayarlar",
      "TitleOnNotificationsTonotification": "Bildirişlər",
      "TitleOnScanntoScannerQr": "QR kodunu skan et",
      "ShowOnScanntoScannerQr": "Göstər",
      "ScanOnScanntoScannerQr": "Skan et",
      "SettingsTitleToSettings": "Ayarlar",
      "AccountToSettings": "Hesab",
      "SettingsLabelToSettings": "Ayarlar",
      "LanguageLabelToSettings": "Dil",
      "NotificationsLabelToSettings": "Bildirişlər",
      "DarkModeLabelToSettings": "Tünd rəng rejimi",
      "HelpLabelToSettings": "Kömək"
    },
    'mo': {
      "letsgetstarted": "Să începem",
      "descriptiononDevine":
          "Lorem Ipsum - este doar un text fictiv folosit în industria poligrafică.",
      "createaccount": "Creează un cont",
      "login": "Autentificare",
      "registration": "Înregistrare",
      "descriptionOnRegistration":
          "Lorem Ipsum - este doar un text fictiv folosit în industria poligrafică.",
      "ContinueOnRegistration": "Continuă",
      "LoginOnLogin": "Autentificare",
      "DescriptionOnLogin":
          "Lorem Ipsum - este doar un text fictiv folosit în industria poligrafică.",
      "ContinueOnLogin": "Continuă",
      "MenuItemsOneOnHome": "Raftul meu",
      "MenuItemsTwoOnHome": "Magazin",
      "MenuItemsThreeOnHome": "Portofoliu",
      "MenuItemsFourOnHome": "Comunicare",
      "MyBookBookshelf": "Cărțile mele",
      "WishlistedBooksBookshelf": "Cărți în listă de dorințe",
      "BookShareGenreList1": "Science fiction",
      "BookShareGenreList2": "Fantezie",
      "BookShareGenreList3": "Detectiv",
      "BookShareGenreList4": "Romantic",
      "BookShareGenreList5": "Thriller",
      "BookShareGenreList6": "Horror",
      "BookShareGenreList7": "Aventură",
      "BookShareGenreList8": "Literatură științifică popularizată",
      "BookShareGenreList9": "Biografie",
      "BookShareGenreList10": "Proză istorică",
      "BookShareGenreList11": "Distopie",
      "BookShareGenreList12": "Poezie",
      "BookShareGenreList13": "Auto-dezvoltare",
      "BookShareGenreList14": "Cărți de bucătărie",
      "BookShareGenreList15": "Roman grafic",
      "BookShareGenreList16": "Literatură pentru tineret",
      "BookShareGenreList17": "Literatură pentru copii",
      "MyBagOnBag": "Portofelul meu",
      "DrawerOnHomeToHomeScreens": "Pagina principală",
      "DrawerOnNewCollectionsToHomeScreens": "Colecții noi",
      "DrawerOnEditorsToHomeScreens": "Recomandări editoriale",
      "DrawerOnTopDealseToHomeScreens": "Cele mai bune oferte",
      "DrawerOnNotificationsToHomeScreens": "Notificări",
      "DrawerOnSettingToHomeScreens": "Setări",
      "TitleOnNotificationsTonotification": "Notificări",
      "TitleOnScanntoScannerQr": "Scanează codul QR",
      "ShowOnScanntoScannerQr": "Afișează",
      "ScanOnScanntoScannerQr": "Scanează",
      "SettingsTitleToSettings": "Setări",
      "AccountToSettings": "Cont",
      "SettingsLabelToSettings": "Setări",
      "LanguageLabelToSettings": "Limba",
      "NotificationsLabelToSettings": "Notificări",
      "DarkModeLabelToSettings": "Mod întunecat",
      "HelpLabelToSettings": "Ajutor"
    },
    'tg': {
      "letsgetstarted": "Ба шурӯъ кунем",
      "descriptiononDevine":
          "Lorem Ipsum - интихоби тексти сатрӣ барои соҳаи چопӣ аст.",
      "createaccount": "Қайд кунед",
      "login": "Ворид шавед",
      "registration": "Регистр",
      "descriptionOnRegistration":
          "Lorem Ipsum - интихоби тексти сатрӣ барои соҳаи چопӣ аст.",
      "ContinueOnRegistration": "Идома диҳед",
      "LoginOnLogin": "Ворид шавед",
      "DescriptionOnLogin":
          "Lorem Ipsum - интихоби тексти сатрӣ барои соҳаи چопӣ аст.",
      "ContinueOnLogin": "Идома диҳед",
      "MenuItemsOneOnHome": "Алманах",
      "MenuItemsTwoOnHome": "Дуконон",
      "MenuItemsThreeOnHome": "Портфолио",
      "MenuItemsFourOnHome": "Интихоб",
      "MyBookBookshelf": "Китобҳои ман",
      "WishlistedBooksBookshelf": "Китобҳои листи омӯзиш",
      "BookShareGenreList1": "Фантастикаи илмӣ",
      "BookShareGenreList2": "Таҳайёсараи илмӣ",
      "BookShareGenreList3": "Ҳунармандӣ",
      "BookShareGenreList4": "Романтик",
      "BookShareGenreList5": "Триллер",
      "BookShareGenreList6": "Ҳай-хуруд",
      "BookShareGenreList7": "Маҳсулот",
      "BookShareGenreList8": "Адабиёти илмӣ-маъруф",
      "BookShareGenreList9": "Зиндагинома",
      "BookShareGenreList10": "Прозаи таърихӣ",
      "BookShareGenreList11": "Дистопия",
      "BookShareGenreList12": "Шеър",
      "BookShareGenreList13": "Худсозӣ",
      "BookShareGenreList14": "Китоби ашпазӣ",
      "BookShareGenreList15": "Роман ҷадид",
      "BookShareGenreList16": "Адабиёти ҷавонон",
      "BookShareGenreList17": "Китобҳои кӯдакон",
      "MyBagOnBag": "Касфҳои ман",
      "DrawerOnHomeToHomeScreens": "Саҳифаи асосӣ",
      "DrawerOnNewCollectionsToHomeScreens": "Қадоми нав",
      "DrawerOnEditorsToHomeScreens": "Танзимоти сунбулгар",
      "DrawerOnTopDealseToHomeScreens": "Беҳтарин пешфарзҳо",
      "DrawerOnNotificationsToHomeScreens": "Огоҳӣ",
      "DrawerOnSettingToHomeScreens": "Танзимот",
      "TitleOnNotificationsTonotification": "Огоҳӣ",
      "TitleOnScanntoScannerQr": "Сканировании коди QR",
      "ShowOnScanntoScannerQr": "Намоиш",
      "ScanOnScanntoScannerQr": "Сканировании",
      "SettingsTitleToSettings": "Танзимотҳо",
      "AccountToSettings": "Ҳисоб",
      "SettingsLabelToSettings": "Танзимотҳо",
      "LanguageLabelToSettings": "Забон",
      "NotificationsLabelToSettings": "Огоҳӣ",
      "DarkModeLabelToSettings": "Режими танҳо",
      "HelpLabelToSettings": "Кумак"
    },
    'ky': {
      "letsgetstarted": "Баштоо",
      "descriptiononDevine":
          "Lorem Ipsum - бул полиграфиялык индустрияда колдонулган фиктивдүү текст.",
      "createaccount": "Аккаунт түзүү",
      "login": "Кируу",
      "registration": "Каттоо",
      "descriptionOnRegistration":
          "Lorem Ipsum - бул полиграфиялык индустрияда колдонулган фиктивдүү текст.",
      "ContinueOnRegistration": "Улантуу",
      "LoginOnLogin": "Кируу",
      "DescriptionOnLogin":
          "Lorem Ipsum - бул полиграфиялык индустрияда колдонулган фиктивдүү текст.",
      "ContinueOnLogin": "Улантуу",
      "MenuItemsOneOnHome": "Раф",
      "MenuItemsTwoOnHome": "Магазин",
      "MenuItemsThreeOnHome": "Портфель",
      "MenuItemsFourOnHome": "Көпөлөк",
      "MyBookBookshelf": "Менин китаптарым",
      "WishlistedBooksBookshelf": "Иштебеткен китаптар",
      "BookShareGenreList1": "Илимий фантастика",
      "BookShareGenreList2": "Фантастика",
      "BookShareGenreList3": "Детектив",
      "BookShareGenreList4": "Романтика",
      "BookShareGenreList5": "Триллер",
      "BookShareGenreList6": "Королкой",
      "BookShareGenreList7": "Македония",
      "BookShareGenreList8": "Илимий-жамоолук адабият",
      "BookShareGenreList9": "Биография",
      "BookShareGenreList10": "Тарыхи проза",
      "BookShareGenreList11": "Дистопия",
      "BookShareGenreList12": "Шеер",
      "BookShareGenreList13": "Өзүн жеткирүү",
      "BookShareGenreList14": "Кулинардык китеп",
      "BookShareGenreList15": "Графикалык роман",
      "BookShareGenreList16": "Жаш жигиттер адабияты",
      "BookShareGenreList17": "Бала адабияты",
      "MyBagOnBag": "Менин портфелим",
      "DrawerOnHomeToHomeScreens": "Башкы бет",
      "DrawerOnNewCollectionsToHomeScreens": "Жаңы коллекциялар",
      "DrawerOnEditorsToHomeScreens": "Бас редактордун тавсиялары",
      "DrawerOnTopDealseToHomeScreens": "Жакшы кагаздар",
      "DrawerOnNotificationsToHomeScreens": "Билдирүүлөр",
      "DrawerOnSettingToHomeScreens": "Орнотуулар",
      "TitleOnNotificationsTonotification": "Билдирүүлөр",
      "TitleOnScanntoScannerQr": "QR-код скан кылуу",
      "ShowOnScanntoScannerQr": "Көрсөтүү",
      "ScanOnScanntoScannerQr": "Скан кылуу",
      "SettingsTitleToSettings": "Орнотуулар",
      "AccountToSettings": "Аккаунт",
      "SettingsLabelToSettings": "Орнотуулар",
      "LanguageLabelToSettings": "Тил",
      "NotificationsLabelToSettings": "Билдирүүлөр",
      "DarkModeLabelToSettings": "Кара мод",
      "HelpLabelToSettings": "Коомак"
    },
    'uz': {
      "letsgetstarted": "Boshlaymiz",
      "descriptiononDevine":
          "Lorem Ipsum - bu matn sifatli matnlar sohasida ishlatiladigan tuzuvchi matn.",
      "createaccount": "Hisob yaratish",
      "login": "Kirish",
      "registration": "Ro'yxatdan o'tish",
      "descriptionOnRegistration":
          "Lorem Ipsum - bu matn sifatli matnlar sohasida ishlatiladigan tuzuvchi matn.",
      "ContinueOnRegistration": "Davom etish",
      "LoginOnLogin": "Kirish",
      "DescriptionOnLogin":
          "Lorem Ipsum - bu matn sifatli matnlar sohasida ishlatiladigan tuzuvchi matn.",
      "ContinueOnLogin": "Davom etish",
      "MenuItemsOneOnHome": "Shkaf",
      "MenuItemsTwoOnHome": "Do'kon",
      "MenuItemsThreeOnHome": "Portfel",
      "MenuItemsFourOnHome": "Muloqot",
      "MyBookBookshelf": "Mening kitoblarim",
      "WishlistedBooksBookshelf": "Istalgan kitoblar",
      "BookShareGenreList1": "Ilmiy fantastika",
      "BookShareGenreList2": "Fantaziya",
      "BookShareGenreList3": "Detektiv",
      "BookShareGenreList4": "Romantika",
      "BookShareGenreList5": "Triller",
      "BookShareGenreList6": "Qo'rqinch",
      "BookShareGenreList7": "Sayohat",
      "BookShareGenreList8": "Ilmiy-mashhur adabiyot",
      "BookShareGenreList9": "Biografiya",
      "BookShareGenreList10": "Tarixiy nasr",
      "BookShareGenreList11": "Distopiya",
      "BookShareGenreList12": "Sherlar",
      "BookShareGenreList13": "O'z-o'zini rivojlantirish",
      "BookShareGenreList14": "Oziq-ovqat kitobi",
      "BookShareGenreList15": "Grafik roman",
      "BookShareGenreList16": "Yosh adabiyoti",
      "BookShareGenreList17": "Bolalar adabiyoti",
      "MyBagOnBag": "Mening portfelim",
      "DrawerOnHomeToHomeScreens": "Bosh sahifa",
      "DrawerOnNewCollectionsToHomeScreens": "Yangi kolleksiyalar",
      "DrawerOnEditorsToHomeScreens": "Tahririyat taqdimoti",
      "DrawerOnTopDealseToHomeScreens": "Eng yaxshi takliflar",
      "DrawerOnNotificationsToHomeScreens": "Bildirishnomalar",
      "DrawerOnSettingToHomeScreens": "Sozlamalar",
      "TitleOnNotificationsTonotification": "Bildirishnomalar",
      "TitleOnScanntoScannerQr": "QR-kodni skan qilish",
      "ShowOnScanntoScannerQr": "Ko'rsatish",
      "ScanOnScanntoScannerQr": "Skan qilish",
      "SettingsTitleToSettings": "Sozlamalar",
      "AccountToSettings": "Hisob",
      "SettingsLabelToSettings": "Sozlamalar",
      "LanguageLabelToSettings": "Til",
      "NotificationsLabelToSettings": "Bildirishnomalar",
      "DarkModeLabelToSettings": "Tungi rejim",
      "HelpLabelToSettings": "Yordam"
    },
    'lv': {
      "letsgetstarted": "Sākam",
      "descriptiononDevine":
          "Lorem Ipsum ir vienkārši fiktīvs teksts, ko izmanto poligrāfijas industrijā.",
      "createaccount": "Izveidot kontu",
      "login": "Ieiet",
      "registration": "Reģistrācija",
      "descriptionOnRegistration":
          "Lorem Ipsum ir vienkārši fiktīvs teksts, ko izmanto poligrāfijas industrijā.",
      "ContinueOnRegistration": "Turpināt",
      "LoginOnLogin": "Ieiet",
      "DescriptionOnLogin":
          "Lorem Ipsum ir vienkārši fiktīvs teksts, ko izmanto poligrāfijas industrijā.",
      "ContinueOnLogin": "Turpināt",
      "MenuItemsOneOnHome": "Grāmatu plaukts",
      "MenuItemsTwoOnHome": "Veikals",
      "MenuItemsThreeOnHome": "Mapes",
      "MenuItemsFourOnHome": "Saziņa",
      "MyBookBookshelf": "Manas grāmatas",
      "WishlistedBooksBookshelf": "Vēlmju saraksta grāmatas",
      "BookShareGenreList1": "Zinātniskā fantastika",
      "BookShareGenreList2": "Fantāzija",
      "BookShareGenreList3": "Detektīvs",
      "BookShareGenreList4": "Romantika",
      "BookShareGenreList5": "Trilleris",
      "BookShareGenreList6": "Briesmu literatūra",
      "BookShareGenreList7": "Piedzīvojumi",
      "BookShareGenreList8": "Zinātniski populārā literatūra",
      "BookShareGenreList9": "Biogrāfija",
      "BookShareGenreList10": "Vēsturiskā proza",
      "BookShareGenreList11": "Distopija",
      "BookShareGenreList12": "Dzeja",
      "BookShareGenreList13": "Pašattīstība",
      "BookShareGenreList14": "Ēdienu grāmata",
      "BookShareGenreList15": "Grafiskā novele",
      "BookShareGenreList16": "Jaunatnes literatūra",
      "BookShareGenreList17": "Bērnu literatūra",
      "MyBagOnBag": "Mana soma",
      "DrawerOnHomeToHomeScreens": "Sākumlapa",
      "DrawerOnNewCollectionsToHomeScreens": "Jaunās kolekcijas",
      "DrawerOnEditorsToHomeScreens": "Redaktoru ieteikumi",
      "DrawerOnTopDealseToHomeScreens": "Labākie piedāvājumi",
      "DrawerOnNotificationsToHomeScreens": "Paziņojumi",
      "DrawerOnSettingToHomeScreens": "Iestatījumi",
      "TitleOnNotificationsTonotification": "Paziņojumi",
      "TitleOnScanntoScannerQr": "Skenēt QR kodu",
      "ShowOnScanntoScannerQr": "Rādīt",
      "ScanOnScanntoScannerQr": "Skenēt",
      "SettingsTitleToSettings": "Iestatījumi",
      "AccountToSettings": "Konts",
      "SettingsLabelToSettings": "Iestatījumi",
      "LanguageLabelToSettings": "Valoda",
      "NotificationsLabelToSettings": "Paziņojumi",
      "DarkModeLabelToSettings": "Tumšais režīms",
      "HelpLabelToSettings": "Palīdzība"
    },
    'lt': {
      "letsgetstarted": "Pradėkime",
      "descriptiononDevine":
          "Lorem Ipsum yra tiesiog išgalvotas tekstas, naudojamas poligrafijos pramonėje.",
      "createaccount": "Sukurti paskyrą",
      "login": "Prisijungti",
      "registration": "Registracija",
      "descriptionOnRegistration":
          "Lorem Ipsum yra tiesiog išgalvotas tekstas, naudojamas poligrafijos pramonėje.",
      "ContinueOnRegistration": "Tęsti",
      "LoginOnLogin": "Prisijungti",
      "DescriptionOnLogin":
          "Lorem Ipsum yra tiesiog išgalvotas tekstas, naudojamas poligrafijos pramonėje.",
      "ContinueOnLogin": "Tęsti",
      "MenuItemsOneOnHome": "Knygų lentyna",
      "MenuItemsTwoOnHome": "Parduotuvė",
      "MenuItemsThreeOnHome": "Portfolio",
      "MenuItemsFourOnHome": "Komunikacija",
      "MyBookBookshelf": "Mano knygos",
      "WishlistedBooksBookshelf": "Norimų knygų sąrašas",
      "BookShareGenreList1": "Mokslinė fantastika",
      "BookShareGenreList2": "Fantastika",
      "BookShareGenreList3": "Detektyvas",
      "BookShareGenreList4": "Romantika",
      "BookShareGenreList5": "Trileris",
      "BookShareGenreList6": "Siaubas",
      "BookShareGenreList7": "Nuotykiai",
      "BookShareGenreList8": "Populiarioji mokslo literatūra",
      "BookShareGenreList9": "Biografija",
      "BookShareGenreList10": "Istorinė proza",
      "BookShareGenreList11": "Distopija",
      "BookShareGenreList12": "Poezija",
      "BookShareGenreList13": "Saviraiška",
      "BookShareGenreList14": "Kulinarijos knyga",
      "BookShareGenreList15": "Grafinis romanėlis",
      "BookShareGenreList16": "Jaunimo literatūra",
      "BookShareGenreList17": "Vaikų literatūra",
      "MyBagOnBag": "Mano piniginė",
      "DrawerOnHomeToHomeScreens": "Pagrindinis puslapis",
      "DrawerOnNewCollectionsToHomeScreens": "Nauji rinkiniai",
      "DrawerOnEditorsToHomeScreens": "Redaktorių rekomendacijos",
      "DrawerOnTopDealseToHomeScreens": "Geriausi pasiūlymai",
      "DrawerOnNotificationsToHomeScreens": "Pranešimai",
      "DrawerOnSettingToHomeScreens": "Nuostatos",
      "TitleOnNotificationsTonotification": "Pranešimai",
      "TitleOnScanntoScannerQr": "Skenavimas QR kodą",
      "ShowOnScanntoScannerQr": "Rodyti",
      "ScanOnScanntoScannerQr": "Skenavimas",
      "SettingsTitleToSettings": "Nuostatos",
      "AccountToSettings": "Paskyra",
      "SettingsLabelToSettings": "Nuostatos",
      "LanguageLabelToSettings": "Kalba",
      "NotificationsLabelToSettings": "Pranešimai",
      "DarkModeLabelToSettings": "Tamsusis režimas",
      "HelpLabelToSettings": "Pagalba"
    },
    'et': {
      "letsgetstarted": "Alustame",
      "descriptiononDevine":
          "Lorem Ipsum on lihtsalt väljamõeldud tekst, mida kasutatakse trükiettevõtluses.",
      "createaccount": "Loo konto",
      "login": "Logi sisse",
      "registration": "Registreerimine",
      "descriptionOnRegistration":
          "Lorem Ipsum on lihtsalt väljamõeldud tekst, mida kasutatakse trükiettevõtluses.",
      "ContinueOnRegistration": "Jätka",
      "LoginOnLogin": "Logi sisse",
      "DescriptionOnLogin":
          "Lorem Ipsum on lihtsalt väljamõeldud tekst, mida kasutatakse trükiettevõtluses.",
      "ContinueOnLogin": "Jätka",
      "MenuItemsOneOnHome": "Raamaturiiul",
      "MenuItemsTwoOnHome": "Pood",
      "MenuItemsThreeOnHome": "Portfell",
      "MenuItemsFourOnHome": "Suhtlus",
      "MyBookBookshelf": "Minu raamatud",
      "WishlistedBooksBookshelf": "Soovitud raamatud",
      "BookShareGenreList1": "Ulme",
      "BookShareGenreList2": "Fantastika",
      "BookShareGenreList3": "Detektiiv",
      "BookShareGenreList4": "Romantika",
      "BookShareGenreList5": "Põnevik",
      "BookShareGenreList6": "Õudus",
      "BookShareGenreList7": "Seiklus",
      "BookShareGenreList8": "Populaarteadus",
      "BookShareGenreList9": "Biograafia",
      "BookShareGenreList10": "Ajalooline proosa",
      "BookShareGenreList11": "Düstoopia",
      "BookShareGenreList12": "Luule",
      "BookShareGenreList13": "Isiklik areng",
      "BookShareGenreList14": "Kokaraamat",
      "BookShareGenreList15": "Graafiline romaan",
      "BookShareGenreList16": "Noortekirjandus",
      "BookShareGenreList17": "Laste kirjandus",
      "MyBagOnBag": "Minu kott",
      "DrawerOnHomeToHomeScreens": "Avaleht",
      "DrawerOnNewCollectionsToHomeScreens": "Uued kogud",
      "DrawerOnEditorsToHomeScreens": "Toimetajate soovitused",
      "DrawerOnTopDealseToHomeScreens": "Parimad pakkumised",
      "DrawerOnNotificationsToHomeScreens": "Teated",
      "DrawerOnSettingToHomeScreens": "Seaded",
      "TitleOnNotificationsTonotification": "Teated",
      "TitleOnScanntoScannerQr": "QR-koodi skaneerimine",
      "ShowOnScanntoScannerQr": "Näita",
      "ScanOnScanntoScannerQr": "Skaneeri",
      "SettingsTitleToSettings": "Seaded",
      "AccountToSettings": "Konto",
      "SettingsLabelToSettings": "Seaded",
      "LanguageLabelToSettings": "Keel",
      "NotificationsLabelToSettings": "Teated",
      "DarkModeLabelToSettings": "Tume režiim",
      "HelpLabelToSettings": "Abi"
    },
    'de': {
      "letsgetstarted": "Los geht's",
      "descriptiononDevine":
          "Lorem Ipsum ist nur ein erfundener Text, der in der Druckindustrie verwendet wird.",
      "createaccount": "Konto erstellen",
      "login": "Anmelden",
      "registration": "Registrierung",
      "descriptionOnRegistration":
          "Lorem Ipsum ist nur ein erfundener Text, der in der Druckindustrie verwendet wird.",
      "ContinueOnRegistration": "Weiter",
      "LoginOnLogin": "Anmelden",
      "DescriptionOnLogin":
          "Lorem Ipsum ist nur ein erfundener Text, der in der Druckindustrie verwendet wird.",
      "ContinueOnLogin": "Weiter",
      "MenuItemsOneOnHome": "Bücherregal",
      "MenuItemsTwoOnHome": "Geschäft",
      "MenuItemsThreeOnHome": "Portfolio",
      "MenuItemsFourOnHome": "Kommunikation",
      "MyBookBookshelf": "Meine Bücher",
      "WishlistedBooksBookshelf": "Merkliste",
      "BookShareGenreList1": "Science-Fiction",
      "BookShareGenreList2": "Fantasy",
      "BookShareGenreList3": "Krimi",
      "BookShareGenreList4": "Romantik",
      "BookShareGenreList5": "Thriller",
      "BookShareGenreList6": "Horror",
      "BookShareGenreList7": "Abenteuer",
      "BookShareGenreList8": "Sachliteratur",
      "BookShareGenreList9": "Biografie",
      "BookShareGenreList10": "Historische Prosa",
      "BookShareGenreList11": "Dystopie",
      "BookShareGenreList12": "Poesie",
      "BookShareGenreList13": "Selbstentwicklung",
      "BookShareGenreList14": "Kochbuch",
      "BookShareGenreList15": "Graphic Novel",
      "BookShareGenreList16": "Jugendliteratur",
      "BookShareGenreList17": "Kinderliteratur",
      "MyBagOnBag": "Meine Tasche",
      "DrawerOnHomeToHomeScreens": "Startseite",
      "DrawerOnNewCollectionsToHomeScreens": "Neue Sammlungen",
      "DrawerOnEditorsToHomeScreens": "Redaktionsempfehlungen",
      "DrawerOnTopDealseToHomeScreens": "Top-Angebote",
      "DrawerOnNotificationsToHomeScreens": "Benachrichtigungen",
      "DrawerOnSettingToHomeScreens": "Einstellungen",
      "TitleOnNotificationsTonotification": "Benachrichtigungen",
      "TitleOnScanntoScannerQr": "QR-Code scannen",
      "ShowOnScanntoScannerQr": "Anzeigen",
      "ScanOnScanntoScannerQr": "Scannen",
      "SettingsTitleToSettings": "Einstellungen",
      "AccountToSettings": "Konto",
      "SettingsLabelToSettings": "Einstellungen",
      "LanguageLabelToSettings": "Sprache",
      "NotificationsLabelToSettings": "Benachrichtigungen",
      "DarkModeLabelToSettings": "Dunkler Modus",
      "HelpLabelToSettings": "Hilfe"
    },
    'fr': {
      "letsgetstarted": "Commençons",
      "descriptiononDevine":
          "Lorem Ipsum est simplement un texte fictif utilisé dans l'industrie de l'impression.",
      "createaccount": "Créer un compte",
      "login": "Se connecter",
      "registration": "Inscription",
      "descriptionOnRegistration":
          "Lorem Ipsum est simplement un texte fictif utilisé dans l'industrie de l'impression.",
      "ContinueOnRegistration": "Continuer",
      "LoginOnLogin": "Se connecter",
      "DescriptionOnLogin":
          "Lorem Ipsum est simplement un texte fictif utilisé dans l'industrie de l'impression.",
      "ContinueOnLogin": "Continuer",
      "MenuItemsOneOnHome": "Étagère",
      "MenuItemsTwoOnHome": "Magasin",
      "MenuItemsThreeOnHome": "Portefeuille",
      "MenuItemsFourOnHome": "Communication",
      "MyBookBookshelf": "Mes livres",
      "WishlistedBooksBookshelf": "Liste de souhaits",
      "BookShareGenreList1": "Science-fiction",
      "BookShareGenreList2": "Fantaisie",
      "BookShareGenreList3": "Détective",
      "BookShareGenreList4": "Romance",
      "BookShareGenreList5": "Thriller",
      "BookShareGenreList6": "Horreur",
      "BookShareGenreList7": "Aventure",
      "BookShareGenreList8": "Littérature scientifique",
      "BookShareGenreList9": "Biographie",
      "BookShareGenreList10": "Prose historique",
      "BookShareGenreList11": "Dystopie",
      "BookShareGenreList12": "Poésie",
      "BookShareGenreList13": "Développement personnel",
      "BookShareGenreList14": "Livre de cuisine",
      "BookShareGenreList15": "Roman graphique",
      "BookShareGenreList16": "Littérature jeunesse",
      "BookShareGenreList17": "Littérature pour enfants",
      "MyBagOnBag": "Mon sac",
      "DrawerOnHomeToHomeScreens": "Accueil",
      "DrawerOnNewCollectionsToHomeScreens": "Nouvelles collections",
      "DrawerOnEditorsToHomeScreens": "Recommandations de l'éditeur",
      "DrawerOnTopDealseToHomeScreens": "Meilleures offres",
      "DrawerOnNotificationsToHomeScreens": "Notifications",
      "DrawerOnSettingToHomeScreens": "Paramètres",
      "TitleOnNotificationsTonotification": "Notifications",
      "TitleOnScanntoScannerQr": "Scanner un code QR",
      "ShowOnScanntoScannerQr": "Afficher",
      "ScanOnScanntoScannerQr": "Scanner",
      "SettingsTitleToSettings": "Paramètres",
      "AccountToSettings": "Compte",
      "SettingsLabelToSettings": "Paramètres",
      "LanguageLabelToSettings": "Langue",
      "NotificationsLabelToSettings": "Notifications",
      "DarkModeLabelToSettings": "Mode sombre",
      "HelpLabelToSettings": "Aide"
    },
    'it': {
      "letsgetstarted": "Iniziamo",
      "descriptiononDevine":
          "Lorem Ipsum è semplicemente un testo fittizio utilizzato nell'industria grafica.",
      "createaccount": "Crea un account",
      "login": "Accedi",
      "registration": "Registrazione",
      "descriptionOnRegistration":
          "Lorem Ipsum è semplicemente un testo fittizio utilizzato nell'industria grafica.",
      "ContinueOnRegistration": "Continua",
      "LoginOnLogin": "Accedi",
      "DescriptionOnLogin":
          "Lorem Ipsum è semplicemente un testo fittizio utilizzato nell'industria grafica.",
      "ContinueOnLogin": "Continua",
      "MenuItemsOneOnHome": "Scaffale",
      "MenuItemsTwoOnHome": "Negozio",
      "MenuItemsThreeOnHome": "Portafoglio",
      "MenuItemsFourOnHome": "Comunicazione",
      "MyBookBookshelf": "I miei libri",
      "WishlistedBooksBookshelf": "Lista dei desideri",
      "BookShareGenreList1": "Fantascienza",
      "BookShareGenreList2": "Fantasy",
      "BookShareGenreList3": "Detective",
      "BookShareGenreList4": "Romantico",
      "BookShareGenreList5": "Thriller",
      "BookShareGenreList6": "Horror",
      "BookShareGenreList7": "Avventura",
      "BookShareGenreList8": "Letteratura scientifica",
      "BookShareGenreList9": "Biografia",
      "BookShareGenreList10": "Narrativa storica",
      "BookShareGenreList11": "Distopia",
      "BookShareGenreList12": "Poesia",
      "BookShareGenreList13": "Sviluppo personale",
      "BookShareGenreList14": "Libro di cucina",
      "BookShareGenreList15": "Romanzo grafico",
      "BookShareGenreList16": "Letteratura per giovani",
      "BookShareGenreList17": "Letteratura per bambini",
      "MyBagOnBag": "Il mio zaino",
      "DrawerOnHomeToHomeScreens": "Pagina principale",
      "DrawerOnNewCollectionsToHomeScreens": "Nuove collezioni",
      "DrawerOnEditorsToHomeScreens": "Raccomandazioni dell'editore",
      "DrawerOnTopDealseToHomeScreens": "Migliori offerte",
      "DrawerOnNotificationsToHomeScreens": "Notifiche",
      "DrawerOnSettingToHomeScreens": "Impostazioni",
      "TitleOnNotificationsTonotification": "Notifiche",
      "TitleOnScanntoScannerQr": "Scansiona il codice QR",
      "ShowOnScanntoScannerQr": "Mostra",
      "ScanOnScanntoScannerQr": "Scansiona",
      "SettingsTitleToSettings": "Impostazioni",
      "AccountToSettings": "Account",
      "SettingsLabelToSettings": "Impostazioni",
      "LanguageLabelToSettings": "Lingua",
      "NotificationsLabelToSettings": "Notifiche",
      "DarkModeLabelToSettings": "Modalità scura",
      "HelpLabelToSettings": "Aiuto"
    },
    'es': {
      "letsgetstarted": "Empecemos",
      "descriptiononDevine":
          "Lorem Ipsum es simplemente un texto ficticio utilizado en la industria gráfica.",
      "createaccount": "Crear cuenta",
      "login": "Iniciar sesión",
      "registration": "Registro",
      "descriptionOnRegistration":
          "Lorem Ipsum es simplemente un texto ficticio utilizado en la industria gráfica.",
      "ContinueOnRegistration": "Continuar",
      "LoginOnLogin": "Iniciar sesión",
      "DescriptionOnLogin":
          "Lorem Ipsum es simplemente un texto ficticio utilizado en la industria gráfica.",
      "ContinueOnLogin": "Continuar",
      "MenuItemsOneOnHome": "Estantería",
      "MenuItemsTwoOnHome": "Tienda",
      "MenuItemsThreeOnHome": "Portafolio",
      "MenuItemsFourOnHome": "Comunicación",
      "MyBookBookshelf": "Mis libros",
      "WishlistedBooksBookshelf": "Lista de deseos",
      "BookShareGenreList1": "Ciencia ficción",
      "BookShareGenreList2": "Fantasía",
      "BookShareGenreList3": "Detective",
      "BookShareGenreList4": "Romance",
      "BookShareGenreList5": "Thriller",
      "BookShareGenreList6": "Terror",
      "BookShareGenreList7": "Aventura",
      "BookShareGenreList8": "Literatura científica",
      "BookShareGenreList9": "Biografía",
      "BookShareGenreList10": "Ficción histórica",
      "BookShareGenreList11": "Distopía",
      "BookShareGenreList12": "Poesía",
      "BookShareGenreList13": "Desarrollo personal",
      "BookShareGenreList14": "Libro de cocina",
      "BookShareGenreList15": "Novela gráfica",
      "BookShareGenreList16": "Literatura juvenil",
      "BookShareGenreList17": "Literatura infantil",
      "MyBagOnBag": "Mi bolsa",
      "DrawerOnHomeToHomeScreens": "Inicio",
      "DrawerOnNewCollectionsToHomeScreens": "Nuevas colecciones",
      "DrawerOnEditorsToHomeScreens": "Recomendaciones del editor",
      "DrawerOnTopDealseToHomeScreens": "Mejores ofertas",
      "DrawerOnNotificationsToHomeScreens": "Notificaciones",
      "DrawerOnSettingToHomeScreens": "Configuración",
      "TitleOnNotificationsTonotification": "Notificaciones",
      "TitleOnScanntoScannerQr": "Escanear código QR",
      "ShowOnScanntoScannerQr": "Mostrar",
      "ScanOnScanntoScannerQr": "Escanear",
      "SettingsTitleToSettings": "Configuración",
      "AccountToSettings": "Cuenta",
      "SettingsLabelToSettings": "Configuración",
      "LanguageLabelToSettings": "Idioma",
      "NotificationsLabelToSettings": "Notificaciones",
      "DarkModeLabelToSettings": "Modo oscuro",
      "HelpLabelToSettings": "Ayuda"
    },
    'pt': {
      "letsgetstarted": "Vamos começar",
      "descriptiononDevine":
          "Lorem Ipsum é simplesmente um texto fictício usado na indústria gráfica.",
      "createaccount": "Criar conta",
      "login": "Entrar",
      "registration": "Registro",
      "descriptionOnRegistration":
          "Lorem Ipsum é simplesmente um texto fictício usado na indústria gráfica.",
      "ContinueOnRegistration": "Continuar",
      "LoginOnLogin": "Entrar",
      "DescriptionOnLogin":
          "Lorem Ipsum é simplesmente um texto fictício usado na indústria gráfica.",
      "ContinueOnLogin": "Continuar",
      "MenuItemsOneOnHome": "Estante",
      "MenuItemsTwoOnHome": "Loja",
      "MenuItemsThreeOnHome": "Portfólio",
      "MenuItemsFourOnHome": "Comunicação",
      "MyBookBookshelf": "Meus livros",
      "WishlistedBooksBookshelf": "Lista de desejos",
      "BookShareGenreList1": "Ficção científica",
      "BookShareGenreList2": "Fantasia",
      "BookShareGenreList3": "Detetive",
      "BookShareGenreList4": "Romance",
      "BookShareGenreList5": "Suspense",
      "BookShareGenreList6": "Terror",
      "BookShareGenreList7": "Aventura",
      "BookShareGenreList8": "Literatura científica",
      "BookShareGenreList9": "Biografia",
      "BookShareGenreList10": "Ficção histórica",
      "BookShareGenreList11": "Distopia",
      "BookShareGenreList12": "Poesia",
      "BookShareGenreList13": "Desenvolvimento pessoal",
      "BookShareGenreList14": "Livro de culinária",
      "BookShareGenreList15": "Romance gráfico",
      "BookShareGenreList16": "Literatura juvenil",
      "BookShareGenreList17": "Literatura infantil",
      "MyBagOnBag": "Minha bolsa",
      "DrawerOnHomeToHomeScreens": "Página inicial",
      "DrawerOnNewCollectionsToHomeScreens": "Novas coleções",
      "DrawerOnEditorsToHomeScreens": "Recomendações do editor",
      "DrawerOnTopDealseToHomeScreens": "Melhores ofertas",
      "DrawerOnNotificationsToHomeScreens": "Notificações",
      "DrawerOnSettingToHomeScreens": "Configurações",
      "TitleOnNotificationsTonotification": "Notificações",
      "TitleOnScanntoScannerQr": "Digitalizar código QR",
      "ShowOnScanntoScannerQr": "Mostrar",
      "ScanOnScanntoScannerQr": "Digitalizar",
      "SettingsTitleToSettings": "Configurações",
      "AccountToSettings": "Conta",
      "SettingsLabelToSettings": "Configurações",
      "LanguageLabelToSettings": "Idioma",
      "NotificationsLabelToSettings": "Notificações",
      "DarkModeLabelToSettings": "Modo escuro",
      "HelpLabelToSettings": "Ajuda"
    },
  };

  String? translate(String key) {
    return _localizedStrings[locale.languageCode]?[key];
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return [
      'ru',
      'uk',
      'en',
      'be',
      'kk',
      'hy',
      'ka',
      'az',
      'mo',
      'tg',
      'ky',
      'uz',
      'lv',
      'lt',
      'et',
      'de',
      'fr',
      'it',
      'es',
      'pt'
    ].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(LocalizationsDelegate<AppLocalizations> old) {
    return false;
  }
}
